travis:
  secure:
    BINSTAR_TOKEN: RDA2zycp3J+ve2v4/IiZld5jh2kQJNPKKPMd66YdMJsH5DBZBcDwcRcYMvdPfRLHWoykiwUPIfaOSJHDnJBCGuEaevvMYWamOPwMU/AFi5b1sZ8h89ignsdw4orwgdIWTJ2EtlM1g2ZcjGyvsHiSLpJH5sQhjreXV4BghKdprWRBZjdvntJo8t+LqroJARfBup+O9UoATmYVljnkyGLTySchXVUI7FhQAgH/mTZtOpB94OUPzkWg5cSC0Bw89TEEEiA5JH/TGCoZ7n/yUdQiFzTVYhS3nGaQgKg4Gb3dxG93LBP9uXhWZ8Utg7Bxd5aZ20OpTf6Zy4l4KousYErJ9tzfr5U9g+CHT40yMtfGhkexzhKmXeb8knbsnd85NODUdqI+ox8G0v0BusyRc5UhIO4kDCCn44jTgpsNsl/gH37+QUZnIHer7mlSo+mbRGJ4vBLGdt+X3wbX86aK3sdALQsEAY3J+CUjm14i/tQXMctTAA+o1uMuQyREAhY0OJTGILD9FcDjgr4TNl7XGW1GS3HcqxsDddqrUfSzTVaVRLo0v6jIfz+pAthYvxuq/j6kfD/IlTVOk9C7NTYi8FDglkbnjPfW6aUYbvjWuGgQLuyGwsxKTWefcr9nXNXnwKc13tI2X+XZe4g558+67PWh1HHIUjhdeEq2GgY4NuqHgrI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
